sudo: required
services:
  - docker
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - OPENVAS_HOST=localhost
  - OPENVAS_USERNAME=admin
  - OPENVAS_PASSWORD=admin
  - OPENVASMD_PORT=9390
before_install:
  - docker pull mikesplain/openvas
  - docker run -d -p 9390:9390 -e OV_PASSWORD=admin mikesplain/openvas
install:
  - "pip install tox-travis coverage coveralls"
script:
  - tox -v
after_success:
  - coverage combine --append
  - coverage report
  - coveralls
after_failure:
  - more .tox/log/* | cat
  - more .tox/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
